{% set name = "typogrify" %}
{% set version = "2.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/typogrify-{{ version }}.tar.gz
  sha256: f0aa004e98032a6e6be4c9da65e7eb7150e36ca3bf508adbcda82b4d003e61ee

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python >=3.6
    - smartypants >=1.8.3

test:
  imports:
    - typogrify
    - typogrify.packages
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mintchaos/typogrify
  summary: Filters to enhance web typography, including support for Django & Jinja templates
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - pmlandwehr
    - ickc
